### ISSUE TITLE
IE11 Campaign publishing broken

### ISSUE THREAD

**Issue by dnsl48** [silverstripe/cwp-recipe-kitchen-sink#35]
## Versions

Browser : IE11, Win7
recipe-kitchen-sink: 2.3.0-rc1
framework: 4.4.0-rc1

## Description

Publish campaign button does not work in IE11.

The functionality works fine in
 - IE11 on `silverstripe/installer 4.4.0-rc1`
 - Chrome on `kitchen-sink` 2.3.0-rc1.

## Potentially related to
 - https://github.com/silverstripe/silverstripe-ckan-registry/issues/207
 - https://github.com/silverstripe/silverstripe-sharedraftcontent/issues/98

## How to reproduce

 - Create a new campaign
 - Create a new page and add it to the campaign
 - Upload an image and add it to the campaign
 - Open the campaigns tab, open the campaign
 - Press "Publish campaign" button

**Comment by robbieaverill** [comment]
In terms of the relation to https://github.com/silverstripe/silverstripe-ckan-registry/issues/207, it could equally be related to https://github.com/silverstripe/silverstripe-sharedraftcontent/issues/98, both of which are errors caused by the React 16 upgrade. We'll need to upgrade them and release new minor versions to fix those issues.

**Comment by ScopeyNZ** [comment]
Both "potentially related" issues are closed now so should we revalidate this issue?

**Comment by dnsl48** [comment]
retested, issue resolved
