### ISSUE TITLE
Fix failing builds

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/cwp-recipe-kitchen-sink#39]
Looks like `master`, `2.3`, and `2.2` are all failing with either recipe-cms or recipe-core.

Master:
https://travis-ci.org/silverstripe/cwp-recipe-kitchen-sink/builds/543134754

2.3:
https://travis-ci.org/silverstripe/cwp-recipe-kitchen-sink/builds/543390973

2.2:
https://travis-ci.org/silverstripe/cwp-recipe-kitchen-sink/builds/543758830

**Comment by robbieaverill** [comment]
2.2 build failures are translations that have been updated without updating the tests. Example failure in kitchen sink https://travis-ci.org/silverstripe/cwp-recipe-kitchen-sink/jobs/543758837 and the upstream equivalent https://travis-ci.org/silverstripe/silverstripe-asset-admin/jobs/543678807. Fixed with https://github.com/silverstripe/silverstripe-asset-admin/commit/58b19fa219923eef6298e9d45079fff57ee4889f.

**Comment by robbieaverill** [comment]
2.3 and master have the same failures from asset migration tests, I've raised an upstream issue for those: https://github.com/silverstripe/silverstripe-assets/issues/289

**Comment by robbieaverill** [comment]
Done
